<?php

namespace AppBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function getData(){
       $genre = $this
            ->findAll();

       return $genre;
    }

}
