<?php

namespace AppBundle\Repository;

/**
 * Series_GenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Series_GenresRepository extends \Doctrine\ORM\EntityRepository
{
}
