<?php

namespace AppBundle\Repository;

/**
 * SerieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SerieRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSearchAffine($name){
        $serie = $this
            ->findBy(
                [],
                ['nom' => 'ASC']
            );

        foreach($serie as $series){
            if(stristr($series->getNom(),$name) != false ){
                $serie_match[] = $series;
            }
        }

        if(empty($serie_match)){
            $serie_match = [];
        }

        return $serie_match;
    }
}
